#server:
#  port: 9999
#
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true # ????????ID????
#          lower-case-service-id: true # ?????????????ID
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user/**
#          filters:
#            - StripPrefix=1 # ???? youlai-auth
##        - id: youlai-admin
##          uri: lb://youlai-admin
##          predicates:
##            - Path=/youlai-admin/**
##          filters:
##            - StripPrefix=1
#
#spring:
#  application:
#    name: gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://localhost:8848

