name: CI
on: # 定义触发事件，push 推送到 main 分支或 pull request
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest # 定义运行的环境
    steps: # 定义步骤
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'adopt' # 指定使用 AdoptOpenJDK 发行版
          
      #- name: Build and package gateway
      #  run: |
      #    cd gateway
      #    mvn clean package -DskipTests
          
      - name: Build and package services
        run: |
          for service in gateway liveVideo-service message-service password-service recommend-service recordVideo-service user-service; do
            cd $service
            mvn clean package -DskipTests -q
            cd ..
          done
          
      - name: Copy JAR files # 将构建生成的 JAR 文件复制到一个临时目录 ./jar-files 中。
        run: |
          mkdir -p ./jar-files
          cp gateway/target/*.jar ./jar-files/
          cp liveVideo-service/target/*.jar ./jar-files/
          cp message-service/target/*.jar ./jar-files/
          cp password-service/target/*.jar ./jar-files/
          cp recommend-service/target/*.jar ./jar-files/
          cp recordVideo-service/target/*.jar ./jar-files/
          cp user-service/target/*.jar ./jar-files/

      - name: Install sshpass # 用密码登ssh
        run: sudo apt-get install -y sshpass

      - name: Stop services on server
        run: |
          export SSHPASS=${{ secrets.REMOTE_PASSWORD }}
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'cd /opt/livestream/backend && ./stop_services.sh'
        
      - name: Upload JAR files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }} # ip或者域名
          username: ${{ secrets.REMOTE_USER }} # root
          password: ${{ secrets.REMOTE_PASSWORD}}
          port: 22
          source: "./jar-files/*"
          target: "/opt/livestream/backend/"
          strip_components: 1 #删掉第一层目录

      - name: Check JAR files on server
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'ls -l /opt/livestream/backend/*.jar'

      - name: Start services on server
        run: |
          export SSHPASS=${{ secrets.REMOTE_PASSWORD }}
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'cd /opt/livestream/backend && ./start_services.sh' #这里start命令没用？


      
